### ISSUE TITLE
Support of Subsystem request?

### ISSUE THREAD

**Issue by KarloX2** [TyrenDe/SSHServer#1]
Hi TyrenDe!

I read thru your Wiki and find this is a very interesting and educational step-by-step introduction that taught me a lot about how SSH basically works. The way you separated the entire task into understandable parts is brilliant.

Two things it seems not to cover so far is (basic) authentication and handling the request of a named subsystem. Both I'd need to make use of the code in a real life application. Do you have plans for this?

Thanks
Karlo

**Comment by TyrenDe** [comment]
Oh! Thanks for the kind words. I don't plan to do any further work with this.  It was mostly an exercise to document SSH and show how to read/process the related RFCs.
