### ISSUE TITLE
Poll() is different in documentation and src code

### ISSUE THREAD

**Issue by xucito** [TyrenDe/SSHServer#2]
Hi,

Great repository, don't know if you still actively maintain just a note:

Documentation for Poll() is different from source code

https://github.com/TyrenDe/SSHServer/wiki/003:-Listening-for-Connections

Code says:
```CSHARP
                Task<Socket> acceptTask = m_Listener.AcceptSocketAsync();
                acceptTask.Wait();

                Socket socket = acceptTask.Result;
```

Documentation says:
```CSHARP
            while (m_Listener.Pending())
            {
                Task acceptTask = m_Listener.AcceptSocketAsync();
                acceptTask.Wait();

                Socket socket = acceptTask.Result;
                m_Logger.LogDebug($"New Client: {socket.RemoteEndPoint.ToString()}");

                // TODO: Create and add client list
            }
```

The documented code throws a error as the Task is not returning a Result.

**Comment by TyrenDe** [comment]
Thanks for catching that. The page actually had the correct thing in there, but the Wiki filtered it out. I had to change them to &amp;lt;Socket&amp;gt;.
